function [q_g,q_g_fit,t_fit, fitresult, gof] = createFit_Gauss2()
%CREATEFIT(T_RATE,Q_G)
%  Create a fit.
%
%  Data for 'heat rate vs time' fit:
%      X Input: t_rate
%      Y Output: q_g
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 11-Mar-2026 12:42:24
[t_new, tamb_new, ts_new,q_g, t_rate]= heat_gen_rate2();

%q_g_abs=abs(q_g);
q_g(q_g<0)=0;
t_rate=t_rate(2:end);
q_g=q_g(2:end);

%% Fit: 'heat rate vs time'.
[xData, yData] = prepareCurveData( t_rate, q_g );

% Set up fittype and options.
ft = fittype( 'gauss2' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.Lower = [-Inf -Inf 0 -Inf -Inf 0];
opts.StartPoint = [9.62645083932855 345 121.411402695017 1.0616919313023 680 206.268279960366];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );
q_g_fit=fitresult(xData);
t_fit=xData;


%% increment by simpson's method for regular data 
q_g_increment= 1:(length(t_fit)-2);
q_g_total = 1:(length(t_fit)-2);

for i = 1:(length(t_fit)-2)
    q_g_increment(i) = 5*(q_g(i)+4*q_g(i+1)+q_g(i+2))/6;
    
end 

for i = 1:(length(t_fit)-2)
    if i==1
        q_g_total(i)= q_g_increment(i);
    else
        q_g_total(i)=q_g_increment(i)+q_g_total(i-1);
    end
end

%% increment by simpson's method for fitted data 
q_g_increment2= 1:(length(t_fit)-2);
q_g_total2 = 1:(length(t_fit)-2);

for i = 1:(length(t_fit)-2)
    q_g_increment2(i) = 5*(q_g_fit(i)+4*q_g_fit(i+1)+q_g_fit(i+2))/6;
    
end 

for i = 1:(length(t_fit)-2)
    if i==1
        q_g_total2(i)= q_g_increment2(i);
    else
        q_g_total2(i)=q_g_increment2(i)+q_g_total2(i-1);
    end
end

%% Plot fit with data.
figure( 'Name', 'CEM II A-M 42.5 N' );
subplot(211),
plot( fitresult, xData, yData,'b-');

legend('q_g vs. t_rate', 'heat rate vs time', 'Location', 'NorthEast', 'Interpreter', 'none' );
% Label axes
title('time elapsed Vs heat generation rate due to hydraulic reaction (CEM II A-M 42.5 N) : gaussian fit(2)');
xlabel( 'time elapsed in minute, (min)', 'Interpreter', 'none' );
ylabel( 'heat generation rate, (J/min-g)', 'Interpreter', 'none' );
grid on
subplot(212),
plot(t_fit(1:end-2),q_g_total,'r-',t_fit(1:end-2),q_g_total2,'b-' );
legend('q_g_total vs time-regular data','q_g_total vs time- fitted data ', ...
    'Location', 'NorthEast', 'Interpreter', 'none' );
% Label axes
title('time elapsed Vs cumulative heat generation rate due to hydration (CEM II A-M 42.5 N)');
xlabel( 'time elapsed in minute, (min)', 'Interpreter', 'none' );
ylabel( 'cumulative heat generation, (J/g)', 'Interpreter', 'none' );
grid on



